---
- name: NIC Configuration
  hosts: webservers

  pre_tasks:
  - name: install package
    yum:
      name: python-jmespath
      state: present
    delegate_to: localhost
    run_once: true
  roles:
    - rhel-system-roles.network

